name: Build

on:
  push:
    branches: '**'
    tags-ignore: '**'

jobs:
  build:
    runs-on: windows-latest

    steps:    
    - name: Check out repo
      uses: actions/checkout@v3
    
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build
      run: |
        msbuild -restore .\BuildInstaller\BuildInstaller.csproj
        msbuild -restore
        mkdir artifacts
        powershell -Command "& { Move-Item BuildInstaller\bin\*.nupkg,*\bin\*\*.msi,*\bin\*\*\*.msi .\artifacts\ }"

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Upload artifacts
      uses: actions/upload-artifact@v3.0.0
      with:
        name: BuildInstallerArtifacts
        if-no-files-found: error
        path: artifacts/